@startuml Store Env Usecase

left to right direction

actor "관리자" as user

package POS버전수신현황API{
  usecase "포스프로그램_등록" AS UC11
  usecase "포스프로그램_검색" AS UC12
  usecase "포스프로그램_매장_등록" AS UC13
  usecase "포스프로그램별_등록매장_조회" AS UC14
  usecase "포스프로그램별_등록매장_수정" AS UC15
  usecase "매장별_포스프로그램_검색" AS UC16
  usecase "매장별_포스프로그램_최종버전_조회" AS UC17
  usecase "매장별_포스프로그램_적용버전_조회" AS UC18
  usecase "엑셀다운로드" AS UC19
  usecase "즐겨찾기추가" AS UC20
  usecase "표시항목추가" AS UC21

}


' 사용자
user --> UC11
user --> UC12
user --> UC13
user --> UC14
user --> UC15
user --> UC16
user --> UC17
user --> UC18
user --> UC19
user --> UC20
user --> UC21

@enduml