@startuml

left to right direction

entity "MN_EQPMN_STTN" as mnEqpmnSttn {
    EQPMN_AS_STTN_PID : INT <<PK>>
    --
    HIST_NO : VARCHAR(20)
    SERIAL_NO : VARCHAR(50)
    CORP_CODE : VARCHAR(7)
    CORP_NM : VARCHAR(50)
    EQPMN_CTG_CODE : VARCHAR(7)
    EQPMN_CTG_NM : VARCHAR(50)
    EQPMN_CODE : VARCHAR(7)
    EQPMN_NM : VARCHAR(50)
    MNFCTUR_DE : INT
    AS_PROCESS_CODE : VARCHAR(7)
    ASSRNC_PD_SE_CODE : VARCHAR(1)
    DLIVY_DE : INT
    AS_COST_CODE : VARCHAR(7)
    AS_COST_PRICE : INT(11)
    AS_REPAIR_PRIME_COST : INT(11)
    PAYMENT_AT : VARCHAR(1)
    CMPLT_DE : INT
    RCEPTER_NM : VARCHAR(50)
    STOCK_DE : INT
    STOCK_FORM_SE_CODE : VARCHAR(1)
    DEFECT_H_NOTE : VARCHAR(400)
    PROCESS_MSG_NOTE : VARCHAR(400)
    ALTRTV_EQPMN_AT : VARCHAR(1)
    ALTRTV_EQPMN_CTG_CODE : VARCHAR(7)
    ALTRTV_EQPMN_CODE : VARCHAR(7)
    ALTRTV_EQPMN_SERIAL_NO : VARCHAR(50)
    ALTRTV_EQPMN_RETURN_AT : VARCHAR(1)
    MNFCTUR_CORP_CODE : VARCHAR(7)
    MNFCTUR_CORP_NM : VARCHAR(50)
    APPRO_NO : VARCHAR(20)
    PROCESS_CORP_NM : VARCHAR(50)
    PROCESS_CORP_CODE : VARCHAR(7)
    AS_SEND_WAYBIL_NO : VARCHAR(50)
    AS_SEND_FORM_CODE : VARCHAR(7)
    AS_SEND_DT : DATETIME
    AS_SENDER_NM : VARCHAR(50)
    AS_RECEIVE_DT : DATETIME
    AS_RECEIVER_NM : VARCHAR(50)
    AS_RETRN_DT : DATETIME
    AS_RETRNER_NM : VARCHAR(50)
    MGMT_CORP_SEND_WAYBIL_NO : VARCHAR(50)
    MGMT_CORP_SEND_DT : DATETIME
    MGMT_CORP_SEND_FORM_CODE : VARCHAR(7)
    MGMT_CORP_SENDER_RETRNER_NM : VARCHAR(50)
    VAN_CODE : VARCHAR(7)
    SYMPTMS_HIGH_CTG_NM : VARCHAR(50)
    SYMPTMS_LOW_CTG1_NM : VARCHAR(50)
    SYMPTMS_LOW_CTG2_NM : VARCHAR(50)
    SYMPTMS_LOW_CTG3_NM : VARCHAR(50)
    SYMPTMS_HIGH_CTG_CODE : VARCHAR(7)
    SYMPTMS_LOW_CTG1_CODE : VARCHAR(7)
    SYMPTMS_LOW_CTG2_CODE : VARCHAR(7)
    SYMPTMS_LOW_CTG3_CODE : VARCHAR(7)
    CORP_TELNO : VARCHAR(20)
    CORP_CELNO : VARCHAR(20)
    CORP_ADRES : VARCHAR(100)
    REG_SE_CODE : VARCHAR(1)
    ACSRY_APDTER_AT : VARCHAR(1)
    ACSRY_SERIAL_CABLE_AT : VARCHAR(1)
    ACSRY_POWER_CORD_AT : VARCHAR(1)
    ACSRY_KEYBOARD_AT : VARCHAR(1)
    ACSRY_MOUSE_AT : VARCHAR(1)
    EXCHNG_CMPNT1_NM : VARCHAR(50)
    EXCHNG_CMPNT2_NM : VARCHAR(50)
    EXCHNG_CMPNT3_NM : VARCHAR(50)
    EXCHNG_CMPNT4_NM : VARCHAR(50)
    EXCHNG_CMPNT5_NM : VARCHAR(50)
    EXCHNG_CMPNT6_NM : VARCHAR(50)
    EXCHNG_CMPNT7_NM : VARCHAR(50)
    EXCHNG_CMPNT8_NM : VARCHAR(50)
    EXCHNG_CMPNT9_NM : VARCHAR(50)
    EXCHNG_CMPNT10_NM : VARCHAR(50)
    PRQUDO_JSON : JSON
    PAYMENT_DT : DATETIME
    PAYER_NM : VARCHAR(50)
    PAYMENT_METHOD_NM : VARCHAR(50)
    PAYMENT_SUCCESS_AT : VARCHAR(1)
    PAYMENT_PRICE : INT(11)
    PAYMENT_PROGRESS_SE_NM : VARCHAR(50)
    CREATOR : VARCHAR(100)
    CREATED_AT : TIMESTAMP
    UPDATER : VARCHAR(100)
    UPDATED_AT : TIMESTAMP
}

@enduml




