@startuml

left to right direction

entity "MN_EQPMN_CORP" as mnEqpmnCorp {
  EQPMN_CORP_PID : INT <<PK>>
  --
  CORP_CODE : VARCHAR(7)
  CORP_NM : VARCHAR(50)
  CORP_SE_CODE : VARCHAR(1)
  REP_NM : VARCHAR(50)
  VAN_CORP_CODE : VARCHAR(7)
  USE_AT : VARCHAR(1)
  POS_PROG_CODE : VARCHAR(7)
  STORE_CODE : VARCHAR(7)
  STORE_NM : VARCHAR(50)
  HARDWARE_INFO : VARCHAR(400)
  USE_CODE : VARCHAR(7)
  CORP_NO : VARCHAR(20)
  COM_NM : VARCHAR(50)
  CORP_TYPE_NM : VARCHAR(50)
  ITEM_NM : VARCHAR(50)
  CORP_TELNO : VARCHAR(20)
  CORP_CELNO : VARCHAR(20)
  CORP_FAXNO : VARCHAR(20)
  STT_CODE : VARCHAR(7)
  CORP_ADRES : VARCHAR(100)
  MGMT_CHARGER_NM : VARCHAR(50)
  MGMT_CHARGER_CELNO : VARCHAR(20)
  STORE_GRD_CODE : VARCHAR(7)
  CORP_GRD_CODE : VARCHAR(7)
  CORP_NOTE : VARCHAR(400)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}

@enduml




