CREATE TABLE `MN_VEHICLE_INFO` (
`VEHICLE_INFO_PID` int NOT NULL AUTO_INCREMENT COMMENT '차량_정보_순번',
`LINE_NO` int NOT NULL DEFAULT 4 COMMENT '호선_번호',
`PV_UNQNO` varchar(50) NOT NULL  COMMENT '편성_고유번호',
`PV_UNQCODE` varchar(14) NOT NULL  COMMENT '편성_고유코드',
`STATION_NO` int   COMMENT '기지_역_번호',
`CAR_CNT` int NOT NULL DEFAULT 10 COMMENT '차량_수',
`LAST_RECEIVE_DT` date   COMMENT '마지막_수신_일시',
`CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_시각',
`UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_시각'
, PRIMARY KEY (`VEHICLE_INFO_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4