@startuml

actor "사용자" as user
participant "Controller" as controller
participant "Service" as service
participant "DAO" as dao
database "DB" as db

' 등급조회
user -> controller : 등급조회
activate controller
controller -> service : (void)
activate service
service -> dao: (void)
activate dao
dao -> db: (void)
activate db
dao <-- db: List
deactivate db
service <-- dao: List
deactivate dao
controller <-- service: ResObj
deactivate service
user <-- controller: JSONObject
deactivate controller

' 등급 일괄 저장
user -> controller : 등급 일괄 저장
activate controller
controller -> service : HashMap(grdList)
activate service
service -> dao: HashMap(grdList)
activate dao
dao -> db: HashMap(grdList)
activate db
dao <-- db: int
deactivate db
service <-- dao: int
deactivate dao
controller <-- service: ResObj
deactivate service
user <-- controller: JSONObject
deactivate controller

' 등급 일괄 삭제
user -> controller : 등급 일괄 삭제
activate controller
controller -> service : HashMap(grdList)
activate service
service -> dao: HashMap(grdList)
activate dao
dao -> db: HashMap(grdList)
activate db
dao <-- db: int
deactivate db
service <-- dao: int
deactivate dao
controller <-- service: ResObj
deactivate service
user <-- controller: JSONObject
deactivate controller

' 등급별 장비 가격 일괄 조회
user -> controller : 등급별 장비 가격 일괄 조회
activate controller
controller -> service : HashMap(grdCode)
activate service
service -> dao: HashMap(grdCode)
activate dao
dao -> db: HashMap(grdCode)
activate db
dao <-- db: List
deactivate db
service <-- dao: List
deactivate dao
controller <-- service: ResObj
deactivate service
user <-- controller: JSONObject
deactivate controller

' 등급별 장비 가격 일괄 저장
user -> controller : 등급별 장비 가격 일괄 저장
activate controller
controller -> service : HashMap(grdCode, eqpmnGrdPriceJson)
activate service
service -> dao: HashMap(grdCode, eqpmnGrdPriceJson)
activate dao
dao -> db: HashMap(grdCode, eqpmnGrdPriceJson)
activate db
dao <-- db: int
deactivate db
service <-- dao: int
deactivate dao
controller <-- service: ResObj
deactivate service
user <-- controller: JSONObject
deactivate controller

@enduml