@startuml

left to right direction

entity "MN_MBR_GRADE" as memberGrade {
  GRD_PID : INT(11) <<pk>>
  --
  GRD_CODE : VARCHAR(7)
  GRD_NM : VARCHAR(50)
  DEF_AT : VARCHAR(1)
  FCHQ_CODE : VARCHAR(7)
  REG_STORE_CODE : VARCHAR(7)
  DSC_RT : FLOAT
  DSC_LMT_WAGE : INT(11)
  SUBS_PT : INT(11)
  MIN_USE_PT : INT(11)
  MAX_USE_PT : INT(11)
  FRS_PRC_PT : INT(11)
  DSC_ACML_AT : VARCHAR(1)
  PT_ACML_AT : VARCHAR(1)
  ACM_SE_CODE : VARCHAR(1)
  ANVR_ACM_SE_CODE : VARCHAR(1)
  ANVR_ACM_RT : FLOAT
  GRD_CVRG_SE_CODE : VARCHAR(1)
  DAY_ADJS_CNT : INT(11)
  ADJS_MAX_WEGE : INT(11)
  CASH_ACM_RT : FLOAT
  CRDT_CARD_ACM_RT : FLOAT
  MTKT_ACM_RT : FLOAT
  TRM_ACM_RT : FLOAT
  COP_ACM_RT : FLOAT
  CSH_RECPT_ACM_RT : FLOAT
  GFTVC_ACM_RT : FLOAT
  AFL_CRD_ACM_RT : FLOAT
  RF_ACM_RT : FLOAT
  CSHBE_ACM_RT : FLOAT
  CREATED_AT : TIMESTAMP
  UPDATED_AT : TIMESTAMP
}

@enduml