@startuml

left to right direction

entity "MN_MBR_CREDIT_H" as mnMbrCreditH {
  MBR_CREDIT_H_PID : int <<pk>>
  --
  FCHQ_CODE : VARCHAR(7)
  STORE_UNQCODE : VARCHAR(14)
  STORE_NM : VARCHAR(50)
  MBR_CODE : VARCHAR(7)
  KO_MBR_NM : VARCHAR(50)
  CREDIT_PRICE : INT(11)
  DEPOSIT_PRICE : INT(11)
  DEPOSIT_METHOD_SECODE : VARCHAR(1)
  APPRO_LOG_NO : VARCHAR(20)
  PROCESS_DT : DATETIME
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}
@enduml