@startuml

left to right direction

entity "MN_MBR_CARD" as memberCard {
  MBR_CARD_PID : INT(11) <<pk>>
  --
  MBR_CARD_H_PID : INT(11)
  NEW_CARDNO : VARCHAR(20)
  PREV_CARDNO : VARCHAR(20)
  CARD_STT_SE_CODE : VARCHAR(1)
  CARD_ISN_SE_CODE : VARCHAR(1)
  CARD_AFL_STORE_CODE : VARCHAR(7)
  CARD_AFL_FCHQ_CODE : VARCHAR(7)
  CARD_ISN_DE : INT(11)
  CARD_ISN_NOTE : VARCHAR(400)
  CREATED_AT : TIMESTAMP
  UPDATED_AT : TIMESTAMP
}

entity "MN_MBR_CARD_H" as memberCardHistory {
  MBR_CARD_H_PID : INT(11) <<pk>>
  --
  MBR_CODE : VARCHAR(7)
  NEW_CARDNO : VARCHAR(20)
  PREV_CARDNO : VARCHAR(20)
  CARD_STT_SE_CODE : VARCHAR(1)
  CARD_ISN_SE_CODE : VARCHAR(1)
  CARD_AFL_FCHQ_CODE : VARCHAR(7)
  CARD_AFL_STORE_CODE : VARCHAR(7)
  CARD_ISN_DE : INT(11)
  CARD_ISN_NOTE : VARCHAR(400)
  CREATED_AT : TIMESTAMP
  UPDATED_AT : TIMESTAMP
}

@enduml