@startuml

left to right direction

entity "MN_MBR_POINT_CHG_H" as mnMbrPointChgH {
  MBR_POINT_CHG_PID : INT(11) <<pk>>
  --
  STORE_MBR_PID : BIGINT
  MBR_CODE : VARCHAR(7)
  KO_MBR_NM : VARCHAR(50)
  STORE_UNQCODE : VARCHAR(14)
  CHG_PT_STORE_UNQCODE : VARCHAR(14)
  CHG_PT_DE : INT(11)
  PREV_HOLD_PT : INT(11)
  NEW_PT : INT(11)
  TRN_PT : INT(11)
  AVLBL_PT : INT(11)
  ADJS_PT : INT(11)
  ACM_PT : INT(11)
  ACM_CANCEL_PT : INT(11)
  USE_PT : INT(11)
  USE_CANCEL_PT : INT(11)
  POINT_NOTE : VARCHAR(400)
  POINT_ENC_VAL : VARCHAR(4000)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}

entity "MN_MBR_POINT" as mnMbrPoint {
  MBR_POINT_PID : BIGINT <<pk>>
  --
  STORE_MBR_PID : BIGINT
  MBR_CODE : VARCHAR(7)
  KO_MBR_NM : VARCHAR(50)
  STORE_UNQCODE : VARCHAR(14)
  ACM_PT : INT(11)
  USE_PT : INT(11)
  ADJS_PT : INT(11)
  AVLBL_PT : INT(11)
  POINT_ENC_VAL : VARCHAR(4000)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}

entity "MN_MBR_POINT_TRN" as mnMbrPointTrn {
  MBR_POINT_TRN_PID :	BIGINT <<pk>>
  --
  STORE_UNQCODE : VARCHAR(14)
  TRN_PT : INT(11)
  SEND_STORE_MBR_PID : BIGINT
  SEND_MBR_CODE : VARCHAR(7)
  SEND_MBR_NM : VARCHAR(50)
  RECEIVE_STORE_MBR_PID : BIGINT
  RECEIVE_MBR_CODE : VARCHAR(7)
  RECEIVE_MBR_NM : VARCHAR(50)
  POINT_ENC_VAL : VARCHAR(4000)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}


@enduml