@startuml

left to right direction

entity "MN_STORE_MBR" as storeMember {
  STORE_MBR_PID : BIGINT <<pk>>
  --
  MBR_CODE : VARCHAR(7)
  MBR_GRD_CODE : VARCHAR(7)
  KO_MBR_NM : VARCHAR(50)
  EN_MBR_NM : VARCHAR(50)
  FCHQ_CODE : VARCHAR(7)
  FCHQ_NM : VARCHAR(50)
  REG_STORE_NM : VARCHAR(50)
  REG_STORE_CODE : VARCHAR(7)
  MBR_CARDNO : VARCHAR(20)
  MBR_CARD_ISSU_CNT : INT(11)
  GENDER : VARCHAR(1)
  CARD_USE_SE_CODE : VARCHAR(1)
  BIRTH_DE : INT(11)
  BIRTH_SE_CODE : VARCHAR(1)
  MBR_MTTL_AT : VARCHAR(1)
  MBR_MTTL_DE : INT(11)
  MBR_TELNO : VARCHAR(20)
  MBR_CELNO : VARCHAR(20)
  SHORT_NO_SE_CODE : VARCHAR(1)
  SHORT_NO : VARCHAR(20)
  MBR_EMAIL : VARCHAR(100)
  MBR_ADRES : VARCHAR(256)
  EMAIL_RCVD_AT : VARCHAR(1)
  SMS_RCVD_AT : VARCHAR(1)
  DM_RCVD_AT : VARCHAR(1)
  USE_AT : VARCHAR(1)
  PREV_HOLD_PT : INT(11)
  INST_STAFF_NM : VARCHAR(50)
  CSH_RECPT_NO : VARCHAR(20)
  MBR_REFER_VAL : VARCHAR(100)
  ACM_PT : INT(11)
  USE_PT : INT(11)
  ADJS_PT : INT(11)
  AVLBL_PT : INT(11)
  MBR_NOTE : VARCHAR(400)
  MBR_JOIN_DE : INT(11)
  ACM_SALES_CNT : INT(11)
  ACM_SALES_PRICE : INT(11)
  FRST_VST_DE : INT(11)
  LAST_VST_DE : INT(11)
  CREATED_AT : TIMESTAMP
  UPDATED_AT : TIMESTAMP
}

@enduml