@startuml

left to right direction

entity "MN_STORE_TCHKEY_GRP" as mnStoreTchkeyGrp {
  TCHKEY_GRP_PID : BIGINT <<pk>>
  --
  STORE_UNQCODE : VARCHAR(14)
  SUB_SE_CODE : VARCHAR(1)
  TCHKEY_GRP_CODE : VARCHAR(7)
  TCHKEY_GRP_PAGE_NO : VARCHAR(20)
  TCHKEY_GRP_IMG_URL : VARCHAR(256)
  TCHKEY_GRP_NM : VARCHAR(50)
  TCHKEY_GRP_X_COOR : FLOAT
  TCHKEY_GRP_Y_COOR : FLOAT
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}

entity "MN_STORE_TCHKEY" as mnStoreTchkey {
  TCHKEY_PID : BIGINT <<pk>>
  --
  STORE_UNQCODE : VARCHAR(14)
  SUB_SE_CODE : VARCHAR(1)
  TCHKEY_GRP_CODE : VARCHAR(7)
  TCHKEY_CODE : VARCHAR(7)
  TCHKEY_PAGE_NO : VARCHAR(20)
  GOODS_CODE : VARCHAR(7)
  GOODS_NM : VARCHAR(50)
  GOODS_PRICE : INT(11)
  TCHKEY_X_COOR : FLOAT
  TCHKEY_Y_COOR : FLOAT
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
  UPDATER : VARCHAR(100)
  UPDATED_AT : TIMESTAMP
}


@enduml