CREATE TABLE `MN_STATION_INFO` (
`STATUS_INFO_PID` int NOT NULL AUTO_INCREMENT COMMENT '역_정보_순번',
`LINE_NO` int NOT NULL DEFAULT 4 COMMENT '호선_번호',
`STATION_NO` int NOT NULL  COMMENT '역_번호',
`STATION_NM` varchar(50) NOT NULL  COMMENT '역_명',
`USE_AT` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용_여부',
`STATION_FLAG` int   COMMENT '역_구분',
`R_STATION_NO` int   COMMENT '오른쪽_역_번호',
`R_STATION2_NO` int   COMMENT '오른쪽_역2_번호',
`L_STATION_NO` int   COMMENT '왼쪽_역_번호',
`CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_시각',
`UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_시각'
, PRIMARY KEY (`STATUS_INFO_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4