CREATE TABLE `MN_HOLIDAY_INFO` (
    `HOLIDAY_INFO_PID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '공휴일_정보_순번',
    `HOLIDAY_YEAR` int NOT NULL COMMENT '공휴일_년도',
    `HOLIDAY_MTH` int NOT NULL COMMENT '공휴일_월',
    `HOLIDAY_DE` int NOT NULL COMMENT '공휴일_일',
    `HOLIDAY_NM` varchar(50) NOT NULL COMMENT '공휴일_명',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시간'
    , PRIMARY KEY (`HOLIDAY_INFO_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4