@startuml Sample Usecase

left to right direction

actor "가맹점/FC본사" as store

package 일자별회원구매내역{
  usecase "일자별회원 구매내역 조회" AS UG10
  usecase "회원별 구매내역 상세조회" AS UG11
  usecase "회원별 상세정보" AS UG12
}

store --> UG10
store --> UG11
store --> UG12
@enduml