@startuml Pos Output Usecase

left to right direction

actor "사용자" as user

package 포스출력물관리API{
  usecase "포스출력물종류 목록" AS UC11
  usecase "포스출력물템플릿 목록" AS UC12
  usecase "포스출력물템플릿 수정" AS UC13
  usecase "포스출력물코드 목록" AS UC14
}

package 포스출력물로그PI{
  usecase "포스출력물로그 목록" AS UC21
}

' 사용자
UC21 <-- user
user --> UC11
user --> UC12
user --> UC13
user --> UC14

@enduml