CREATE TABLE `MN_POS_M`
(
    `POS_PID`          bigint       NOT NULL AUTO_INCREMENT COMMENT '포스_순번',
    `STORE_UNQCODE`    varchar(14)  NOT NULL COMMENT '매장_고유코드',
    `FCHQ_CODE`        varchar(7)   NOT NULL COMMENT '본사_코드',
    `POS_PROG_VER_PID` bigint COMMENT '포스_프로그램_버전_순번',
    `FCHQ_NM`          varchar(50)  NOT NULL COMMENT '본사_명',
    `STORE_NM`         varchar(50)  NOT NULL COMMENT '매장_명',
    `POS_NO`           varchar(20)  NOT NULL COMMENT '포스_번호',
    `POS_NM`           varchar(50) COMMENT '포스_명',
    `TABLE_GRP_PID`    int(11) COMMENT '테이블_그룹_순번',
    `CONTRACT_NO`      varchar(20) COMMENT '계약_번호',
    `SERIAL_NO`        varchar(20) COMMENT '일련_번호',
    `CONFRM_AT`        varchar(1) COMMENT '인증_여부',
    `INIT_CONFRM_DT`   datetime COMMENT '최초_인증_일시',
    `LAST_CONFRM_DT`   datetime COMMENT '최종_인증_일시',
    `CONFRM_CNT`       int(11) COMMENT '인증_수',
    `SW_CRTF_NO`       varchar(20) COMMENT 'SW_인증_번호',
    `HW_CRTF_NO`       varchar(20) COMMENT 'HW_인증_번호',
    `POS_SE_CODE`      varchar(1)   NOT NULL COMMENT '포스_구분_코드',
    `POS_FORM_SE_CODE` varchar(1)   NOT NULL COMMENT '포스_형태_구분_코드',
    `PAYMENT_SE_CODE`  varchar(1)   NOT NULL COMMENT '지불_구분_코드',
    `POS_PROG_VER_NO`  varchar(20) COMMENT '포스_프로그램_버전_번호',
    `LAST_LOGIN_DT`    datetime COMMENT '최종_로그인_일시',
    `LAST_LOGIN_IP`    varchar(23) COMMENT '최종_로그인_ip',
    `POS_IP`           varchar(23) COMMENT '포스_IP',
    `CREATOR`          varchar(100) NOT NULL COMMENT '작성자',
    `CREATED_AT`       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일시',
    `UPDATER`          varchar(100) NOT NULL COMMENT '수정자',
    `UPDATED_AT`       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`POS_PID`),
    INDEX mn_pos_m_idx (`STORE_UNQCODE`, `CREATED_AT`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4