@startuml

left to right direction

entity "PM_MBLCPN_APPRO" as pmMbrcpnAppro {
  MBLCPN_APPRO_PID : BIGINT
  --
  STORE_NM : VARCHAR(50)
  SALES_DE : INT
  POS_NO : VARCHAR(20)
  RECPT_NO : VARCHAR(20)
  CPN_SE_CODE : VARCHAR(1)
  CPN_BARCODE_VAL : VARCHAR(100)
  APPRO_NO : VARCHAR(20)
  LOG_NO : VARCHAR(20)
  APPRO_PRICE : INT(11)
  APPRO_DE : INT
  APPRO_DT : DATE
  CPN_PRICE : INT(11)
  RMNNG_PRICE : INT(11)
  CPN_USE_ENC_VAL : VARCHAR(4000)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
}

entity "PM_MBLCPN_GOODS_APPRO" as pmMbrcpnGoodsAppro {
  MBLCPN_APPRO_G_PID : BIGINT
  --
  STORE_NM : VARCHAR(50)
  SALES_DE : INT
  POS_NO : VARCHAR(20)
  RECPT_NO : VARCHAR(20)
  CPN_SE_CODE : VARCHAR(1)
  CPN_BARCODE_VAL : VARCHAR(100)
  APPRO_NO : VARCHAR(20)
  LOG_NO : VARCHAR(20)
  APPRO_PRICE : INT(11)
  APPRO_DE : INT
  APPRO_DT : DATE
  GOODS_CODE : VARCHAR(7)
  GOODS_NM : VARCHAR(50)
  SALES_CNT : INT(11)
  GOODS_PRICE : INT(11)
  ACTL_SALES_PRICE : INT(11)
  CPN_USE_ENC_VAL : VARCHAR(4000)
  CREATOR : VARCHAR(100)
  CREATED_AT : TIMESTAMP
}

@enduml