CREATE TABLE `ENV_PREFER` (
    `ENV_PREFER_PID` int NOT NULL AUTO_INCREMENT COMMENT '환경_설정_일련번호',
    `ENV_PREFER_CODE` varchar(7) NOT NULL  COMMENT '환경_설정_코드',
    `ENV_PREFER_NM` varchar(50) NOT NULL  COMMENT '환경_설정_명',
    `ENV_CODE` varchar(7) NOT NULL  COMMENT '환경_코드',
    `USE_AT` varchar(1) NOT NULL  COMMENT '사용_여부',
    `CREATOR` varchar(100) NOT NULL  COMMENT '작성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시'
    , PRIMARY KEY (`ENV_PREFER_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4