CREATE TABLE `MN_EQPMN_AS_STTN` (
    `EQPMN_AS_STTN_PID` int NOT NULL AUTO_INCREMENT COMMENT '장비_AS_현황_일련번호',
    `HIST_NO` varchar(20) NOT NULL  COMMENT '이력_번호',
    `SERIAL_NO` varchar(50) NOT NULL  COMMENT '일련_번호',
    `CORP_CODE` varchar(7) NOT NULL  COMMENT '업체_코드',
    `CORP_NM` varchar(50) NOT NULL  COMMENT '업체_명',
    `EQPMN_CTG_CODE` varchar(7) NOT NULL  COMMENT '장비_분류_코드',
    `EQPMN_CTG_NM` varchar(50) NOT NULL  COMMENT '장비_분류_명',
    `EQPMN_CODE` varchar(7) NOT NULL  COMMENT '장비_코드',
    `EQPMN_NM` varchar(50) NOT NULL  COMMENT '장비_명',
    `MNFCTUR_DE` int   COMMENT '제조_일자',
    `AS_PROCESS_CODE` varchar(7) NOT NULL DEFAULT '7220001' COMMENT 'AS_처리_코드',
    `ASSRNC_PD_SE_CODE` varchar(1) NOT NULL  COMMENT '보증_기간_구분_코드',
    `DLIVY_DE` int   COMMENT '출고_일자',
    `AS_COST_CODE` varchar(7) NOT NULL  COMMENT 'AS_비용_코드',
    `AS_COST_PRICE` int(11) NOT NULL DEFAULT 0 COMMENT 'AS_비용_가격',
    `AS_REPAIR_PRIME_COST` int(11) NOT NULL DEFAULT 0 COMMENT 'AS_수리_원_가',
    `CMPLT_DE` int   COMMENT '완료_일자',
    `RCEPTER_STAFF_NM` varchar(50)   COMMENT '접수자_사원_명',
    `RCEPTER_STAFF_ID` varchar(100)   COMMENT '접수자_사원_ID',
    `RCEPTER_DEPT_CODE` varchar(7)   COMMENT '접수자_부서_코드',
    `STOCK_DE` int NOT NULL  COMMENT '입고_일자',
    `STOCK_FORM_SE_CODE` varchar(1)   COMMENT '입고_형태_구분_코드',
    `DEFECT_H_NOTE` varchar(400)   COMMENT '고장_내역_비고',
    `PROCESS_MSG_NOTE` varchar(400)   COMMENT '처리_사항_비고',
    `ALTRTV_EQPMN_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '대체_장비_여부',
    `ALTRTV_EQPMN_CTG_CODE` varchar(7)   COMMENT '대체_장비_분류_코드',
    `ALTRTV_EQPMN_CODE` varchar(7)   COMMENT '대체_장비_코드',
    `ALTRTV_EQPMN_SERIAL_NO` varchar(50)   COMMENT '대체_장비_일련_번호',
    `ALTRTV_EQPMN_RETURN_AT` varchar(1)   COMMENT '대체_장비_회수_여부',
    `MNFCTUR_CORP_CODE` varchar(7)   COMMENT '제조_업체_코드',
    `MNFCTUR_CORP_NM` varchar(50)   COMMENT '제조_업체_명',
    `APPRO_NO` varchar(20)   COMMENT '승인_번호',
    `PROCESS_CORP_NM` varchar(50)   COMMENT '처리_업체_명',
    `PROCESS_CORP_CODE` varchar(7) NOT NULL  COMMENT '처리_업체_코드',
    `AS_SEND_WAYBIL_NO` varchar(50)   COMMENT 'AS_발송_운송장_번호',
    `AS_SEND_FORM_CODE` varchar(7)   COMMENT 'AS_발송_형태_코드',
    `AS_SEND_DT` datetime   COMMENT 'AS_발송_일시',
    `AS_SENDER_NM` varchar(50)   COMMENT 'AS_발송자_명',
    `AS_RECEIVE_DT` datetime   COMMENT 'AS_수령_일시',
    `AS_RECEIVER_NM` varchar(50)   COMMENT 'AS_수령자_명',
    `AS_RETRN_DT` datetime   COMMENT 'AS_반송_일시',
    `AS_RETRNER_NM` varchar(50)   COMMENT 'AS_반송자_명',
    `MGMT_CORP_SEND_WAYBIL_NO` varchar(50)   COMMENT '관리_업체_발송_운송장_번호',
    `MGMT_CORP_SEND_DT` datetime NOT NULL  COMMENT '관리_업체_발송_일시',
    `MGMT_CORP_SEND_FORM_CODE` varchar(7)   COMMENT '관리_업체_발송_형태_코드',
    `MGMT_CORP_SENDER_RECEIVER_NM` varchar(50)   COMMENT '관리_업체_발송자_수령자_명',
    `VAN_CODE` varchar(7)   COMMENT 'VAN사_코드',
    `SYMPTMS_HIGH_CTG_NM` varchar(50)   COMMENT '증상_대_분류_명',
    `SYMPTMS_LOW_CTG1_NM` varchar(50)   COMMENT '증상_소_분류1_명',
    `SYMPTMS_LOW_CTG2_NM` varchar(50)   COMMENT '증상_소_분류2_명',
    `SYMPTMS_LOW_CTG3_NM` varchar(50)   COMMENT '증상_소_분류3_명',
    `SYMPTMS_HIGH_CTG_CODE` varchar(7)   COMMENT '증상_대_분류_코드',
    `SYMPTMS_LOW_CTG1_CODE` varchar(7)   COMMENT '증상_소_분류1_코드',
    `SYMPTMS_LOW_CTG2_CODE` varchar(7)   COMMENT '증상_소_분류2_코드',
    `SYMPTMS_LOW_CTG3_CODE` varchar(7)   COMMENT '증상_소_분류3_코드',
    `CORP_TELNO` varchar(20)   COMMENT '업체_전화번호',
    `CORP_CELNO` varchar(20)   COMMENT '업체_핸드폰번호',
    `CORP_ADRES` varchar(100)   COMMENT '업체_주소',
    `REG_SE_CODE` varchar(1)   COMMENT '등록_구분_코드',
    `ACSRY_APDTER_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '악세사리_아답터_여부',
    `ACSRY_SERIAL_CABLE_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '악세사리_시리얼_케이블_여부',
    `ACSRY_POWER_CORD_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '악세사리_파워_코드_여부',
    `ACSRY_KEYBOARD_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '악세사리_키보드_여부',
    `ACSRY_MOUSE_AT` varchar(1) NOT NULL DEFAULT 'N' COMMENT '악세사리_마우스_여부',
    `EXCHNG_CMPNT1_NM` varchar(50)   COMMENT '교체_부품1_명',
    `EXCHNG_CMPNT2_NM` varchar(50)   COMMENT '교체_부품2_명',
    `EXCHNG_CMPNT3_NM` varchar(50)   COMMENT '교체_부품3_명',
    `EXCHNG_CMPNT4_NM` varchar(50)   COMMENT '교체_부품4_명',
    `EXCHNG_CMPNT5_NM` varchar(50)   COMMENT '교체_부품5_명',
    `EXCHNG_CMPNT6_NM` varchar(50)   COMMENT '교체_부품6_명',
    `EXCHNG_CMPNT7_NM` varchar(50)   COMMENT '교체_부품7_명',
    `EXCHNG_CMPNT8_NM` varchar(50)   COMMENT '교체_부품8_명',
    `EXCHNG_CMPNT9_NM` varchar(50)   COMMENT '교체_부품9_명',
    `EXCHNG_CMPNT10_NM` varchar(50)   COMMENT '교체_부품10_명',
    `PRQUDO_JSON` JSON   COMMENT '견적서_json',
    `PAYMENT_AT` varchar(1)  DEFAULT 'N' COMMENT '결제_여부',
    `PAYMENT_DT` datetime   COMMENT '결제_일시',
    `PAYER_NM` varchar(50)   COMMENT '결제자_명',
    `PAYMENT_METHOD_NM` varchar(50)   COMMENT '결제_수단_명',
    `PAYMENT_SUCCESS_AT` varchar(1)   COMMENT '결제_성공_여부',
    `PAYMENT_PRICE` int(11)   COMMENT '결제_금액',
    `PAYMENT_PROGRESS_SE_NM` varchar(50)   COMMENT '결재_진행_구분_명',
    `CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_일시'
    , PRIMARY KEY (`EQPMN_AS_STTN_PID`)
    , INDEX mn_eqpmn_as_sttn_idx (`CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4