CREATE TABLE `MN_EQPMN_CORP` (
    `EQPMN_CORP_PID` int NOT NULL AUTO_INCREMENT COMMENT '장비_업체_일련번호',
    `CORP_CODE` varchar(7) NOT NULL  COMMENT '업체_코드',
    `CORP_NM` varchar(50) NOT NULL  COMMENT '업체_명',
    `EQPMN_CORP_SE_CODE` varchar(1) NOT NULL  COMMENT '장비_업체_구분_코드',
    `REP_NM` varchar(50)   COMMENT '대표자_명',
    `VAN_CORP_CODE` varchar(7)   COMMENT '밴사_코드',
    `USE_AT` varchar(1) NOT NULL  COMMENT '사용_여부',
    `POS_PROG_CODE` varchar(7)   COMMENT '포스_프로그램_코드',
    `STORE_CODE` varchar(7)   COMMENT '매장_코드',
    `STORE_NM` varchar(50)   COMMENT '매장_명',
    `HARDWARE_INFO` varchar(400)   COMMENT '하드웨어_정보',
    `USE_CODE` varchar(7)   COMMENT '용도_코드',
    `CORP_NO` varchar(20)   COMMENT '사업자_번호',
    `COM_NM` varchar(50)   COMMENT '상호_명',
    `CORP_TYPE_NM` varchar(50)   COMMENT '업태_명',
    `ITEM_NM` varchar(50)   COMMENT '종목_명',
    `CORP_TELNO` varchar(20)   COMMENT '전화번호',
    `CORP_CELNO` varchar(20)   COMMENT '휴대폰번호',
    `CORP_FAXNO` varchar(20)   COMMENT '팩스번호',
    `STT_CODE` varchar(7)   COMMENT '상태_코드',
    `CORP_ADRES` varchar(100)   COMMENT '업체_주소',
    `MGMT_CHARGER_NM` varchar(50)   COMMENT '관리_담당자_명',
    `MGMT_CHARGER_CELNO` varchar(20)   COMMENT '관리_담당자_휴대폰번호',
    `STORE_GRD_CODE` varchar(7)   COMMENT '매장_등급_코드',
    `CORP_GRD_CODE` varchar(7)   COMMENT '업체_등급_코드',
    `CORP_NOTE` varchar(400)   COMMENT '업체_비고',
    `CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_일시'
    , PRIMARY KEY (`EQPMN_CORP_PID`)
    , CONSTRAINT mn_eqpmn_corp_uk UNIQUE (`CORP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4