CREATE TABLE `MN_EQPMN_CTG` (
    `EQPMN_CTG_PID` int NOT NULL AUTO_INCREMENT COMMENT '장비_분류_일련번호',
    `EQPMN_CTG_CODE` varchar(7) NOT NULL  COMMENT '장비_분류_코드',
    `EQPMN_CTG_NM` varchar(50) NOT NULL  COMMENT '장비_분류_명',
    `CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_일시'
    , PRIMARY KEY (`EQPMN_CTG_PID`)
    , CONSTRAINT mn_eqpmn_ctg_uk UNIQUE (`EQPMN_CTG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4