CREATE TABLE `MN_EQPMN_SYMPTMS` (
    `EQPMN_SYMPTMS_PID` int NOT NULL AUTO_INCREMENT COMMENT '장비_증상_일련번호',
    `SYMPTMS_CTG_SE_CODE` varchar(1) NOT NULL  COMMENT '증상_분류_구분_코드',
    `SYMPTMS_CTG_PARENT_CODE` varchar(7) NOT NULL  COMMENT '증상_분류_부모_코드',
    `SYMPTMS_CTG_CODE` varchar(7) NOT NULL  COMMENT '증상_분류_코드',
    `SYMPTMS_CTG_NM` varchar(50) NOT NULL  COMMENT '증상_분류_명',
    `USE_AT` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용_여부',
    `CREATOR` varchar(100) NOT NULL  COMMENT '생성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_일시'
    , PRIMARY KEY (`EQPMN_SYMPTMS_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4