CREATE TABLE `MN_FIX_DSC` (
  `FIX_DSC_PID` int NOT NULL AUTO_INCREMENT COMMENT '고정_할인_순번',
  `DSC_SE_TYPE_CODE` varchar(7) NOT NULL DEFAULT 0 COMMENT '할인_구분_유형_코드',
  `DSC_CODE` varchar(7) NOT NULL COMMENT '할인_코드',
  `DSC_PRICE` int NOT NULL DEFAULT 0 COMMENT '할인_금액',
  `AUTO_CLOSE_AT` varchar(1) NOT NULL COMMENT '자동_닫기_여부',
  `USE_AT` varchar(1) NOT NULL COMMENT '사용_여부',
  `CREATOR` varchar(100) NOT NULL COMMENT '작성자',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
  `UPDATER` varchar(100) NOT NULL COMMENT '수정자',
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '변경시간'
  , PRIMARY KEY (`FIX_DSC_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4