CREATE TABLE `MN_GIFT_CARD` (
    `GIFT_CARD_PID` int NOT NULL AUTO_INCREMENT COMMENT '상품권_순번',
    `STORE_UNQCODE` varchar(14) NOT NULL  COMMENT '매장_고유코드',
    `CTG_CODE` varchar(7) NOT NULL  COMMENT '분류_코드',
    `GIFT_CARD_CODE` varchar(7) NOT NULL  COMMENT '상품권_코드',
    `GIFT_CARD_NM` varchar(50) NOT NULL  COMMENT '상품권_명',
    `PRICE` int(11) NOT NULL DEFAULT 0 COMMENT '액면가',
    `USE_AT` varchar(1) NOT NULL  COMMENT '사용_여부',
    `CREATOR` varchar(100) NOT NULL  COMMENT '작성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '변경시간'
    , PRIMARY KEY (`GIFT_CARD_PID`)
    , CONSTRAINT `fk_mn_payment_method_ctg_mn_gift_card_1` FOREIGN KEY (`CTG_CODE`) REFERENCES `MN_PAYMENT_METHOD_CTG` (`CTG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4