CREATE TABLE `MN_FCHQ_M` (
    `FCHQ_PID` int NOT NULL AUTO_INCREMENT COMMENT '본사_일련번호',
    `FCHQ_CODE` varchar(4) NOT NULL  COMMENT '본사_코드',
    `FCHQ_NM` varchar(50) NOT NULL  COMMENT '본사_명',
    `REP_NM` varchar(50) NOT NULL  COMMENT '대표자_명',
    `CORP_NO` varchar(20) NOT NULL  COMMENT '사업자_번호',
    `COM_NM` varchar(50) NOT NULL  COMMENT '상호_명',
    `FCHQ_TYPE_NM` varchar(50) NOT NULL  COMMENT '업태_명',
    `FCHQ_ITEM_NM` varchar(50) NOT NULL  COMMENT '종목_명',
    `FCHQ_TELNO` varchar(20) NOT NULL  COMMENT '전화번호',
    `FCHQ_CELNO` varchar(20)   COMMENT '핸드폰',
    `FCHQ_FAXNO` varchar(20)   COMMENT '팩스',
    `LOCAL_CODE` varchar(7) NOT NULL  COMMENT '지역_코드',
    `STT_CODE` varchar(7) NOT NULL  COMMENT '상태_코드',
    `SYS_OPEN_DE` int NOT NULL  COMMENT '시스템_오픈_일자',
    `FCHQ_EMAIL` varchar(100)   COMMENT 'E-mail',
    `FCHQ_STOCK_OPEN_AT` varchar(1) NOT NULL  COMMENT '본사_재고_오픈_여부',
    `WEBSITE_URL` varchar(256)   COMMENT '웹사이트_url',
    `POST_NO` varchar(20) NOT NULL  COMMENT '우편_번호',
    `ROADNM_ADRES` varchar(100) NOT NULL  COMMENT '도로명_주소',
    `DETAIL_ADRES` varchar(100)   COMMENT '상세_주소',
    `USE_CODE` varchar(7) NOT NULL  COMMENT '용도_코드',
    `BRAND_AT` varchar(1) NOT NULL  COMMENT '브랜드_여부',
    `SALE_MARGIN_AT` varchar(1) NOT NULL  COMMENT '판매_마진_여부',
    `PROD_CATE_CODE` varchar(7) NOT NULL  COMMENT '상품_분류_코드',
    `MGMT_VAN_CODE` varchar(7) NOT NULL  COMMENT '관리_밴사_코드',
    `MGMT_CORP_CODE` varchar(7) NOT NULL  COMMENT '관리업체_코드',
    `SYS_NOTE` varchar(400)   COMMENT '시스템_비고',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_시각',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_시각'
    , PRIMARY KEY (`FCHQ_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4