CREATE TABLE `MN_STM_KIT_MEMO` (
   `KIT_MEMO_PID` int NOT NULL AUTO_INCREMENT COMMENT '주방_메모_일련번호',
   `STORE_CODE` varchar(7) NOT NULL  COMMENT '매장_코드',
   `MEMO_CODE` varchar(2) NOT NULL  COMMENT '메모_코드',
   `MEMO` varchar(30)   COMMENT '메모',
   `USE_AT` varchar(1) NOT NULL DEFAULT Y COMMENT '사용_여부',
   `CREATOR` varchar(100) NOT NULL  COMMENT '작성자',
   `UPDATOR` varchar(100) NOT NULL  COMMENT '수정자',
   `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
   `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시간'
    , PRIMARY KEY (`KIT_MEMO_PID`)
    , CONSTRAINT `fk_mn_stm_m_mn_stm_kit_memo_1` FOREIGN KEY (`STORE_CODE`) REFERENCES `MN_STM_M` (`STORE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4