CREATE TABLE `MN_PARTNER_CARD` (
  `PARTNER_CARD_PID` int NOT NULL AUTO_INCREMENT COMMENT '제휴_카드_순번',
  `STORE_UNQCODE` varchar(14) NOT NULL  COMMENT '매장_고유코드',
  `PARTNER_TYPE_CODE` varchar(7) NOT NULL  COMMENT '제휴_유형_코드',
  `PARTNER_CODE` varchar(7) NOT NULL COMMENT '제휴_코드',
  `PARTNER_NM` varchar(50) NOT NULL COMMENT '제휴명',
  `START_EXPIRE_DE` int NOT NULL COMMENT '시작_유효_기간',
  `END_EXPIRE_DE` int NOT NULL COMMENT '종료_유효_기간',
  `DSC_SE_CODE` varchar(1) NOT NULL COMMENT '할인_구분코드',
  `DSC_RT` float NOT NULL DEFAULT 0 COMMENT '할인_율',
  `DSC_LMT_SE_CODE` varchar(1) NOT NULL COMMENT '할인_한도_구분코드',
  `DSC_LMT_PRICE` int NOT NULL DEFAULT 0 COMMENT '할인_한도_금액',
  `APPRO_SE_CODE` varchar(1) NOT NULL  COMMENT '승인처리_구분코드',
  `PARTNER_NOTE` varchar(400) COMMENT '비고',
  `USE_AT` varchar(1) NOT NULL COMMENT '사용_여부',
  `CREATOR` varchar(100) NOT NULL COMMENT '작성자',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
  `UPDATER` varchar(100) NOT NULL COMMENT '수정자',
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '변경시간'
  , PRIMARY KEY (`PARTNER_CARD_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4