CREATE TABLE `MN_PAYMENT_METHOD_CTG` (
    `PAYMENT_METHOD_CTG_PID` int NOT NULL AUTO_INCREMENT COMMENT '결제_수단_분류_순번',
    `STORE_UNQCODE` varchar(14) NOT NULL COMMENT '매장_고유코드',
    `PAYMENT_METHOD_SE_CODE` varchar(1) NOT NULL COMMENT '결제_수단_구분코드',
    `CTG_CODE` varchar(7) NOT NULL COMMENT '분류_코드',
    `CTG_NM` varchar(50) NOT NULL COMMENT '분류명',
    `USE_AT` varchar(1) NOT NULL COMMENT '사용_여부',
    `CREATOR` varchar(100) NOT NULL COMMENT '작성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    `UPDATER` varchar(100) NOT NULL COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '변경시간'
    , PRIMARY KEY (`PAYMENT_METHOD_CTG_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4