CREATE TABLE `MN_SALE_STATS`
(
    `STATS_PID`                  int         NOT NULL AUTO_INCREMENT COMMENT '샘플_일련번호',
    `STORE_UNQCODE`              varchar(14) NOT NULL COMMENT '매장_고유코드',
    `STORE_NM`                   varchar(50) NOT NULL COMMENT '매장_명',
    `SALE_DE`                    int         NOT NULL COMMENT '판매_일자',
    `SALE_AT`                    datetime    NOT NULL COMMENT '판매_시간',
    `SALE_SE_CODE`               varchar(1) COMMENT '판매_구분_코드',
    `SALE_POS_NO`                varchar(20) NOT NULL COMMENT '판매_포스_번호',
    `ORDER_NO`                   varchar(20) NOT NULL COMMENT '주문_번호',
    `RECEIPT_NO`                 varchar(20) NOT NULL COMMENT '영수증번호',
    `BARCODE_VAL`                varchar(100) COMMENT '바코드_값',
    `HIGH_CTG_CODE`              varchar(7) COMMENT '대_분류_코드',
    `HIGH_CTG_NM`                varchar(50) COMMENT '대_분류_명',
    `MID_CTG_CODE`               varchar(7) COMMENT '중_분류_코드',
    `MID_CTG_NM`                 varchar(50) NOT NULL COMMENT '중_분류_명',
    `LOW_CTG_CODE`               varchar(7)  NOT NULL COMMENT '소_분류_코드',
    `LOW_CTG_NM`                 varchar(50) NOT NULL COMMENT '소_분류_명',
    `STORE_GCODE`                varchar(20) NOT NULL COMMENT '매장_상품코드',
    `GOODS_NM`                   varchar(50) COMMENT '상품_명',
    `SIDE_CTG_CODE`              varchar(7) COMMENT '사이드메뉴_분류_코드',
    `SIDE_CTG_NM`                varchar(50) COMMENT '사이드메뉴_분류_명',
    `SIDE_GRP_CODE`              varchar(7) COMMENT '사이드메뉴_그룹_코드',
    `SIDE_GRP_NM`                varchar(50) COMMENT '사이드메뉴_그룹_명',
    `SIDE_STORE_GCODE` COMMENT '사이드메뉴_상품_코드',
    `SIDE_GOODS_NM` COMMENT '사이드메뉴_상품_명',
    `SIDE_CTG_COST`              int(11) COMMENT '사이드_메뉴_단가',
    `SIDE_CTG_CNT`               int(11) COMMENT '사이드_메뉴_수량',
    `SIDE_CTG_PRICE`             int(11) COMMENT '사이드_메뉴_매출액',
    `INIT_SALE_PRICE`            int(11) COMMENT '초기_판매_금액',
    `SALE_CNT`                   int(11)              DEFAULT 0 COMMENT '판매_수량',
    `SALE_PRICE`                 int(11)              DEFAULT 0 COMMENT '판매_금액',
    `ACT_SALE_PRICE`             int(11)              DEFAULT 0 COMMENT '실제_매출_금액',
    `TIP_PRICE`                  int(11)              DEFAULT 0 COMMENT '봉사료_금액',
    `OVERCHARGE_PRICE`           int(11) COMMENT '에누리_금액',
    `VAT_PRICE`                  int(11)              DEFAULT 0 COMMENT '부가_금액',
    `PRICE`                      int(11)              DEFAULT 0 COMMENT '가액',
    `ACM_PT`                     int(11)     NOT NULL DEFAULT 0 COMMENT '적립_포인트',
    `USE_PT`                     int(11)     NOT NULL DEFAULT 0 COMMENT '사용_포인트',
    `PAYMENT_NO`                 varchar(20) COMMENT '결제_번호',
    `PAYMENT_DT`                 datetime COMMENT '결제_일시',
    `PAYMENT_SUM_PRICE`          int(11)              DEFAULT 0 COMMENT '결제_합계_금액',
    `SIMPLE_CASH_PRICE`          int(11)              DEFAULT 0 COMMENT '단순_현금_금액',
    `CASH_PRICE`                 int(11)              DEFAULT 0 COMMENT '현금영수_금액',
    `CREDIT_CARD_PRICE`          int(11)              DEFAULT 0 COMMENT '신용_카드_금액',
    `CREDIT_PRICE`               int(11)              DEFAULT 0 COMMENT '외상_금액',
    `GIFT_CARD_PRICE`            int(11)              DEFAULT 0 COMMENT '상품권_금액',
    `MEAL_TICKET_PRICE`          int(11)              DEFAULT 0 COMMENT '식권_금액',
    `MBR_POINT_PRICE`            int(11)              DEFAULT 0 COMMENT '회원_포인트_금액',
    `PARTNER_CARD_PRICE`         int(11)              DEFAULT 0 COMMENT '제휴_카드_금액',
    `STAFF_CARD_PRICE`           int(11)              DEFAULT 0 COMMENT '사원_카드_금액',
    `MOBILE_COUPON_PRICE`        int(11)              DEFAULT 0 COMMENT '모바일_쿠폰_금액',
    `CASHBEE_PRICE`              int(11)              DEFAULT 0 COMMENT '캐시비_금액',
    `PREPAID_CARD_PRICE`         int(11)              DEFAULT 0 COMMENT '선불_카드_금액',
    `ONLINE_PAYMENT_PRICE`       int(11)              DEFAULT 0 COMMENT '온라인_결제_금액',
    `DISCOUNT_PRICE`             int(11) COMMENT '할인_금액',
    `DISCOUNT_SE_CODE`           varchar(1) COMMENT '할인_구분_코드',
    `NORMAL_DISCOUNT_PRICE`      int(11)              DEFAULT 0 COMMENT '일반_할인_금액',
    `SERVICE_DISCOUNT_PRICE`     int(11)              DEFAULT 0 COMMENT '서비스_할인_금액',
    `PARTNER_DISCOUNT_PRICE`     int(11)              DEFAULT 0 COMMENT '제휴_할인_금액',
    `COUPON_DISCOUNT_PRICE`      int(11)              DEFAULT 0 COMMENT '쿠폰_할인_금액',
    `MBR_DISCOUNT_PRICE`         int(11)              DEFAULT 0 COMMENT '회원_할인_금액',
    `MEAL_TICKET_DISCOUNT_PRICE` int(11)              DEFAULT 0 COMMENT '식권_할인_금액',
    `PACKAGE_DISCOUNT_PRICE`     int(11)              DEFAULT 0 COMMENT '포장_할인_금액',
    `YAP_DISCOUNT_PRICE`         int(11)              DEFAULT 0 COMMENT 'YAP_할인_금액',
    `DELIVERY_AT`                varchar(1) COMMENT '배달여부',
    `RETURN_AT`                  varchar(1) COMMENT '반품여부',
    `CANCEL_AT`                  varchar(1) COMMENT '취소여부',
    `WEATHER`                    varchar(10) COMMENT '날씨',
    `STAFF_NO`                   varchar(10) COMMENT '판매원_번호',
    `ORDERER`                    varchar(10) COMMENT '주문자',
    `MBR_CODE`                   varchar(7) COMMENT '회원_코드',
    `KO_MBR_NM`                  varchar(50) COMMENT '한글_회원_명',
    `EN_MBR_NM`                  varchar(50) COMMENT '영어_회원_명',
    `MBR_CARDNO`                 varchar(20) COMMENT '회원_카드_번호',
    `MBR_GRD_CODE`               varchar(7) COMMENT '회원_등급_코드',
    `MBR_GRD_NM`                 varchar(50) COMMENT '회원_등급_명',
    `MBR_DSC_RT`                 float COMMENT '회원_할인_율',
    `MALE_CUSTOMER_CNT`          int(11) COMMENT '남자_고객_수',
    `FEMALE_CUSTOMER_CNT`        int(11) COMMENT '여자_고객_수',
    `TABLE_NM`                   varchar(50)          DEFAULT 0 COMMENT '테이블_명',
    `TABLE_CNT`                  int(11) COMMENT '테이블_수',
    `FIRST_ORDER_DT`             datetime    NOT NULL COMMENT '최초_주문_시간',
    `VENDOR_NM`                  varchar(50) COMMENT '거래처_명',
    `BRAND_NM`                   varchar(50) COMMENT '브랜드_명',
    `POST_REFUND_PRICE`          int(11) COMMENT '사후_환금_금액',
    `RIGHT_REFUND_PRICE`         int(11) COMMENT '즉시_환급_금액',
    `REFUND_FEE_PRICE`           int(11) COMMENT '환급_수수료_금액',
    `CREATED_AT`                 timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    `UPDATED_AT`                 timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시간',
    PRIMARY KEY (`STATS_PID`),
    INDEX mn_sale_stats_idx (`STORE_UNQCODE`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;



