CREATE TABLE `MN_STORE_ACNT_MGMT` (
    `STORE_ACNT_MGMT_PID` int NOT NULL AUTO_INCREMENT COMMENT '매장_계정_관리_일련번호',
    `FCHQ_CODE` varchar(7) NOT NULL  COMMENT '본사_코드',
    `STORE_UNQCODE` varchar(14)   COMMENT '매장_고유코드',
    `VAULTCASH_ACNT_CODE` varchar(7) NOT NULL  COMMENT '시재_계정_코드',
    `VAULTCASH_ACNT_NM` varchar(50) NOT NULL  COMMENT '시재_계정_명',
    `USE_AT` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용_여부',
    `RCPPAY_SE_CODE` varchar(1) NOT NULL  COMMENT '입출금_구분_코드',
    `CREATOR` varchar(100) NOT NULL  COMMENT '작성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일시',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시'
    , PRIMARY KEY (`STORE_ACNT_MGMT_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4