CREATE TABLE `MN_STM_VAN_CHG_H` (
    `STM_VAN_CHG_PID` int NOT NULL AUTO_INCREMENT COMMENT '매장_밴사_변경_순번',
    `STORE_UNQCODE` varchar(14) NOT NULL  COMMENT '매장_고유코드',
    `STORE_NM` varchar(50) NOT NULL  COMMENT '매장명',
    `CORNER_NM` varchar(50) NOT NULL  COMMENT '코너명',
    `STT_CODE` varchar(7) NOT NULL  COMMENT '상태_코드',
    `USE_CODE` varchar(7) NOT NULL  COMMENT '용도_코드',
    `BEFORE_DEF_VAN_NM` varchar(50)   COMMENT '변경전_기본_VAN사_명',
    `BEFORE_DEF_VAN_CODE` varchar(7)   COMMENT '변경전_기본_VAN사_코드',
    `BEFORE_DEF_VAN_CONTRACT_NO` varchar(50)   COMMENT '변경전_기본_VAN사_계약_번호',
    `BEFORE_DEF_VAN_SERIAL_NO` varchar(50)   COMMENT '변경전_기본_VAN사_일련_번호',
    `BEFORE_CASH_VAN_NM` varchar(50)   COMMENT '변경전_현금영수증_VAN사_명',
    `BEFORE_CASH_VAN_CODE` varchar(7)   COMMENT '변경전_현금영수증_VAN사_코드',
    `BEFORE_CASH_VAN_CONTRACT_NO` varchar(50)   COMMENT '변경전_현금영수증_VAN사_계약_번호',
    `BEFORE_CASH_VAN_SERIAL_NO` varchar(50)   COMMENT '변경전_현금영수증_VAN사_일련_번호',
    `BEFORE_OK_CONTRACT_NO` varchar(50)   COMMENT '변경전_OK캐쉬백_계약_번호',
    `BEFORE_OK_SERIAL_NO` varchar(50)   COMMENT '변경전_OK캐쉬백_일련_번호',
    `AFTER_DEF_VAN_NM` varchar(50)   COMMENT '변경후_기본_VAN사_명',
    `AFTER_DEF_VAN_CODE` varchar(7)   COMMENT '변경후_기본_VAN사_코드',
    `AFTER_DEF_VAN_CONTRACT_NO` varchar(50)   COMMENT '변경후_기본_VAN사_계약_번호',
    `AFTER_DEF_VAN_SERIAL_NO` varchar(50)   COMMENT '변경후_기본_VAN사_일련_번호',
    `AFTER_CASH_VAN_NM` varchar(50)   COMMENT '변경후_현금영수증_VAN사_명',
    `AFTER_CASH_VAN_CODE` varchar(7)   COMMENT '변경후_현금영수증_VAN사_코드',
    `AFTER_CASH_VAN_CONTRACT_NO` varchar(50)   COMMENT '변경후_현금영수증_VAN사_계약_번호',
    `AFTER_CASH_VAN_SERIAL_NO` varchar(50)   COMMENT '변경후_현금영수증_VAN사_일련_번호',
    `AFTER_OK_CONTRACT_NO` varchar(50)   COMMENT '변경후_OK캐쉬백_계약_번호',
    `AFTER_OK_SERIAL_NO` varchar(50)   COMMENT '변경후_OK캐쉬백_일련_번호',
    `CREATOR` varchar(100) NOT NULL  COMMENT '작성자',
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    `UPDATER` varchar(100) NOT NULL  COMMENT '수정자',
    `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '변경시간'
    , PRIMARY KEY (`STM_VAN_CHG_PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4