CREATE TABLE `MN_STM_ENV_CODE` (
    `ENV_PID` int NOT NULL AUTO_INCREMENT COMMENT '환경_일련번호',
    `TYPE_CODE` VARCHAR(7) NOT NULL COMMENT '유형_코드',
    `USE_CODE` VARCHAR(7) NOT NULL COMMENT '용도_코드',
    `TAB_CODE` VARCHAR(7) NOT NULL COMMENT '탭_코드',
    `GROUP_CODE` VARCHAR(7) NOT NULL COMMENT '그룹_코드',
    `ENV_CODE` VARCHAR(7) NOT NULL COMMENT '환경_코드',
    `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성_시간',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정_시간',
    PRIMARY KEY (`ENV_PID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4