@startuml

left to right direction

entity "MN_FCHQ_M" as mnFchqM {
  FCHQ_PID : int <<pk>>
  --
  FCHQ_CODE : VARCHAR(4)
  FCHQ_NM : VARCHAR(100)
  REP_NM : VARCHAR(50)
  CORP_NO : VARCHAR(10)
  COM_NM : VARCHAR(50)
  FCHQ_TYPE_NM : VARCHAR(50)
  FCHQ_ITEM_NM : VARCHAR(50)
  FCHQ_TELNO : VARCHAR(20)
  FCHQ_CELNO : VARCHAR(20)
  FCHQ_FAXNO : VARCHAR(20)
  LOCAL_CODE : VARCHAR(7)
  STT_CODE : VARCHAR(7)
  SYS_OPEN_DE : DATE
  FCHQ_EMAIL : VARCHAR(100)
  FCHQ_STOCK_OPEN_AT : VARCHAR(1)
  WEBSITE_URL : VARCHAR(256)
  POST_NO : VARCHAR(20)
  ROADNM_ADRES : VARCHAR(20)
  DETAIL_ADRES : VARCHAR(20)
  USE_CODE : VARCHAR(7)
  BRAND_AT : VARCHAR(1)
  SALE_MARGIN_AT : VARCHAR(1)
  PROD_CATE_CODE : VARCHAR(7)
  MGMT_VAN_CODE : VARCHAR(7)
  MGMT_CORP_CODE : VARCHAR(7)
  SYS_NOTE : VARCHAR(400)
  UPDATED_AT : TIMESTAMP
  CREATED_AT : TIMESTAMP
}



@enduml