@startuml

left to right direction

entity "MN_FIX_DSC" as mnGiftCard {
  FIX_DSC_PID : int <<pk>>
  --
  STORE_UNQCODE : varchar(14)
  DSC_SE_TYPE_CODE : varchar(7)
  DSC_CODE : varchar(7)
  DSC_PRICE : int
  AUTO_CLOSE_AT : varchar(1)
  USE_AT : varchar(1)
  CREATOR : varchar(50)
  CREATED_AT : timestamp
  UPDATER : varchar(50)
  UPDATED_AT : timestamp
}

@enduml