@startuml

left to right direction

entity "MN_MEAL_TICKET" as mnGiftCard {
  MEAL_TICKET_PID : int <<pk>>
  --
  STORE_UNQCODE : varchar(14)
  CTG_CODE : varchar(7)
  MEAL_TICKET_CODE : varchar(7)
  MEAL_TICKET_NM : varchar(50)
  PRICE : int
  USE_AT : varchar(1)
  CREATOR : varchar(50)
  CREATED_AT : timestamp
  UPDATER : varchar(50)
  UPDATED_AT : timestamp
}

@enduml